repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-toml
      - id: debug-statements

  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3.10

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
      - id: ruff
        args: [--fix, --ignore, E402]
      - id: ruff-format

  # Skip mypy and bandit in pre-commit for speed - run them manually or in CI
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.8.0
  #   hooks:
  #     - id: mypy
  #       args: [--ignore-missing-imports]
  #
  # - repo: https://github.com/PyCQA/bandit
  #   rev: 1.8.6
  #   hooks:
  #     - id: bandit
  #       args: [-r, ., -f, json, -o, bandit-report.json]
  #       exclude: ^tests/
  #       pass_filenames: false
  #       always_run: true
