# Dental Backend Settings Template
# Copy this file to settings.yaml and modify as needed for your environment

# Environment Configuration
environment: development  # development, staging, production, testing
debug: true

# Database Configuration
database:
  url: postgresql://dental_user:dental_password@localhost:5432/dental_backend
  pool_size: 10
  max_overflow: 20
  echo: false

# Redis Configuration
redis:
  url: redis://localhost:6379/0
  max_connections: 10

# S3 Configuration (MinIO for local development)
s3:
  endpoint_url: http://localhost:9000
  access_key_id: minioadmin
  secret_access_key: minioadmin
  bucket_name: dental-scans
  region_name: us-east-1
  use_ssl: false

# Security Configuration
security:
  secret_key: your-secret-key-here-change-in-production
  algorithm: HS256
  access_token_expire_minutes: 30
  refresh_token_expire_days: 7
  kms_key_id: null  # AWS KMS key ID for encryption
  encryption_enabled: true
  tls_cert_file: null  # TLS certificate file path
  tls_key_file: null   # TLS private key file path
  rate_limit_requests: 100
  rate_limit_window: 60

# Logging Configuration
logging:
  level: INFO  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: json  # json or text
  file_path: null  # Optional log file path

# API Configuration
api:
  host: 0.0.0.0
  port: 8000
  workers: 1
  reload: true
  cors_origins:
    - "*"

# Worker Configuration (Celery)
worker:
  broker_url: redis://localhost:6379/0
  result_backend: redis://localhost:6379/0
  task_serializer: json
  result_serializer: json
  accept_content:
    - json
  timezone: UTC
  enable_utc: true
  task_track_started: true
  task_time_limit: 1800  # 30 minutes
  task_soft_time_limit: 1500  # 25 minutes

# File Processing Configuration
max_file_size_mb: 100
allowed_file_types:
  - stl
  - ply
  - obj
  - gltf
  - glb
temp_dir: /tmp/dental-backend

# File Upload Configuration
upload:
  presigned_url_expiry: 3600  # 1 hour
  max_concurrent_uploads: 5
  chunk_size_mb: 10
  validation_timeout: 300  # 5 minutes

# Antivirus Configuration
antivirus:
  enabled: true
  clamav_host: localhost
  clamav_port: 3310
  scan_timeout: 30
  max_file_size_scan_mb: 100

# File Validation Configuration
validation:
  max_vertices: 1000000  # 1M vertices
  max_faces: 2000000     # 2M faces
  max_file_size_mb: 100
  allowed_mime_types:
    - application/octet-stream
    - model/stl
    - model/ply
    - model/obj
    - model/gltf+json
    - model/gltf-binary
  scan_3d_models: true

# HIPAA/GDPR Compliance Configuration
data_retention_days: 2555  # 7 years for HIPAA compliance
audit_log_enabled: true
encryption_enabled: true
pii_encryption_enabled: true
phi_logging_enabled: false
pseudonymization_enabled: true
soft_delete_enabled: true
data_purge_enabled: true

# Production Environment Overrides
# Uncomment and modify these settings for production deployment
# environment: production
# debug: false
# security:
#   secret_key: ${SECRET_KEY}  # Use environment variable
# database:
#   url: ${DATABASE_URL}  # Use environment variable
# redis:
#   url: ${REDIS_URL}  # Use environment variable
# s3:
#   endpoint_url: ${S3_ENDPOINT_URL}  # Use environment variable
#   access_key_id: ${S3_ACCESS_KEY_ID}  # Use environment variable
#   secret_access_key: ${S3_SECRET_ACCESS_KEY}  # Use environment variable
# logging:
#   level: WARNING
#   format: json
# api:
#   reload: false
#   workers: 4
